export function mcpCliHelpText(): string {
  return [
    "mcp - use available MCP tools",
    "Supported: search, list, call, and run.",
    "Run `mcp <command> --help` for complete command syntax.",
    "Use this session-local `mcp` command, not `mcporter` or `npx mcporter`; it enforces the materialized recipe capabilities.",
    "",
    "Find tools:",
    "  mcp search \"what you need\"",
    "  mcp search \"tool|argument\" --regex --json",
    "  mcp list",
    "  mcp list <server>",
    "  mcp list <server.tool> --schema",
    "  Add --brief for compact signatures, --all-parameters for every optional input, or --json for machine output.",
    "  Use only one output-mode flag at a time: --brief, --schema, --all-parameters, --json, or --status.",
    "  Exact --schema output includes both input and output schemas, with the output schema after the input schema. Do not truncate it with head or sed.",
    "",
    "Call one tool:",
    "  mcp call <server>.<tool> key=value ...",
    "  Use --json for nested or structured arguments.",
    "  Calls support --output text|markdown|json|raw, --save-images, --timeout, and @file.",
    "  Quote argument tokens containing shell operators, especially multi-value |.",
    "  Use --output json for machine-readable success and failure envelopes.",
    "  When parsing JSON, keep stderr separate and do not truncate stdout with head or sed.",
    "",
    "Run a short workflow:",
    "  mcp run <<'EOF'",
    '  const ids = ["id-1", "id-2", "id-3"]',
    '  const results = await Promise.all(ids.map(id => tools["server"]["tool"]({ id })))',
    "  console.log(JSON.stringify(results.map(result => ({ id: result.id, name: result.name })), null, 2))",
    "  EOF",
    "  Keep the heredoc quoted (<<'EOF'); pass dynamic values with --var KEY=value (read as vars.KEY).",
    "  Calls return decoded JSON by default. Use tool.text(args), tool.markdown(args), tool.images(args), tool.content(args), tool.structuredContent(args), or tool.raw(args) only when the tool documentation calls for another shape.",
    "  Use Promise.all for independent reads. Await dependent calls and mutations in order.",
    "",
    "When to use:",
    "  Use search when you do not know the right tool.",
    "  Inspect a tool's inputs and outputs with mcp list <server.tool> --schema.",
    "  Use mcp call for a single simple operation.",
    "  Use mcp run for multiple calls, filtering, ranking, hydration, or deduplication.",
    "  Do not loop over mcp call in the shell. Use mcp run for repeated calls and print only the fields needed.",
    "  Use @file for long text and --output json when piping call output.",
    "  Tool commands are always headless. If authentication is required, ask the user to authenticate the MCP connection outside the agent session, then retry.",
    "",
    "Availability:",
    "  Search and list expose only tools callable in this session.",
    "  Only exact tool names returned by mcp list are callable.",
    "  Descriptions may mention related tools that are not exposed; mentions do not grant access.",
    "  If no listed tool supports an action, report that the connected capability is unavailable.",
    "  MCP resources and mcporter configuration, ad-hoc transport, code-generation, record/replay, daemon, and serve commands are not exposed.",
  ].join("\n");
}
