export function mcpCliHelpText(): string {
  return [
    "mcp - use available MCP tools",
    "Supported: search, list, call, and run.",
    "Run `mcp <command> --help` for complete command syntax.",
    "Use this session-local `mcp` command, not `mcporter` or `npx mcporter`; it enforces the materialized recipe capabilities.",
    "",
    "Recommended flow:",
    "  mcp search \"what you need\"",
    "  mcp list <server.tool> --schema",
    "  mcp call <server>.<tool> key=value ...",
    "  Search for a tool, inspect its compact contract, then call it.",
    "  Metadata is compact text; actual structured tool results are JSON.",
    "",
    "Batch or compose multiple calls in JavaScript:",
    "  mcp run <<'JS'",
    '  const ids = ["id-1", "id-2", "id-3"]',
    '  const results = await Promise.all(ids.map(id => tools["server"]["tool"]({ id })))',
    "  console.log(JSON.stringify(results.map(result => ({ id: result.id, name: result.name })), null, 2))",
    "  JS",
    "  Keep the heredoc quoted (<<'JS'). Use run for batching, parallel calls, or dependent workflows—not for a single call.",
    "",
    "Notes:",
    "  Use mcp list or mcp list <server> only when you need to browse the available inventory.",
    "  Run `mcp call --help` or `mcp run --help` for advanced argument, output, and workflow options.",
    "  Tool commands are always headless. If authentication is required, ask the user to authenticate the MCP connection outside the agent session, then retry.",
    "",
    "Availability:",
    "  Search and list expose only tools callable in this session.",
    "  Only exact tool names returned by mcp list are callable.",
    "  Descriptions may mention related tools that are not exposed; mentions do not grant access.",
    "  If no listed tool supports an action, report that the connected capability is unavailable.",
    "  MCP resources and administrative or ad-hoc connection commands are not exposed.",
  ].join("\n");
}
